---
title: "Data Visualization"
author: "Philip C. Riege"
---

# Challenge 4.1

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(data.table)
library(lubridate)
library(ggplot2)
library(ggrepel)
library(glue)

covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>%
  select(location, date, total_cases) %>%
  filter(location %in% c("Europe", "Germany", "United Kingdom", "France", "Spain", "United States"))

covid_data_tbl %>%
  
  #plot cases over date
  ggplot(aes(x = date, y = total_cases, color = location)) +
  
  #line plot
  geom_line() +
  
  #scales for the x and y axis
  scale_x_date(labels = scales::label_date(format = "%b '%y"), date_breaks = "1 month") +
  scale_y_continuous(labels = scales::label_number(scale = 1e-6, prefix = "", suffix = " M")) +
  
  #add axis labels and title
  labs(
    title = "COVID-19 confirmed cases worldwide",
    subtitle = glue("As of {date}",
                    date=format(max(covid_data_tbl$date),"%d/%m/%Y")),
    caption = "Challenge 1",
    x = "",
    y = "Cumulative Cases",
    color = "Continent / Country",
  )+
  
  #choose minimal theme and modify
  theme_minimal()+
  theme(legend.position = "bottom",
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0.5, size = 12),
        axis.text.x = element_text(angle = 45, hjust =1),
        plot.title = element_text(size=12),
        plot.subtitle  = element_text(size=9),
        legend.text = element_text(size = 7),
        legend.title = element_text(size = 9),
        )
```

# Challenge 4.2

I had some difficulties with this task. As can be seen from the plot, for some countries no values for the death rate could be obtained. These regions for which the entry at the death rate then is na, are colored gray.

```{r}
#| message: false
#| warning: false
library("tidyverse")
library("readxl")
library("lubridate")
library("data.table")
library("vroom")
library("scales")
library("ggthemes")
library("gapminder")
library("ggplot2")
library("forcats")
library("readxl")
library("ggrepel")
library("glue")

world <- map_data("world")

covid_data <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>%
  mutate(location = case_when(
    
    location == "United Kingdom" ~ "UK",
    location == "United States" ~ "USA",
    location == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
    TRUE ~ location
    
  )) %>%
  distinct() %>%
  group_by(location) %>%
  slice(which.max(as.Date(date))) %>%
  select(location, total_deaths, population,date) %>%
  mutate(death_rate = total_deaths/population)

cov_data_world <-  world %>%
  left_join(covid_data, by = c("region"="location")) %>%
  select(long, lat, group, order, region, subregion, everything())
  
cov_data_world %>% ggplot() +
  geom_map( aes(long, lat, map_id = region, fill = death_rate), 
            map = cov_data_world,
            color = "grey",
            size = 0.09
  )+
  scale_fill_gradient(low = "#FFC6C6", high = "#FF0000", na.value = "grey")
```